summary removed

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -55,19 +55,19 @@ jobs:
         run: |
             ${{matrix.cmd}} ${{ steps.file_changes.outputs.files_modified }}
       
-      - name: Linting summary
-        if: steps.isort.outcome != 'success' || steps.black.outcome != 'success' || steps.pylint.outcome != 'success'
-        run:
-          if [ "${{steps.isort.outcome}}" != "success" ]; then
-            echo "Linting with isort failed."
-          fi
+      # - name: Linting summary
+      #   if: steps.isort.outcome != 'success' || steps.black.outcome != 'success' || steps.pylint.outcome != 'success'
+      #   run:
+      #     if [ "${{steps.isort.outcome}}" != "success" ]; then
+      #       echo "Linting with isort failed."
+      #     fi
 
-          if [ "${{steps.black.outcome}}" != "success" ]; then
-            echo "Linting with black failed."
-          fi
+      #     if [ "${{steps.black.outcome}}" != "success" ]; then
+      #       echo "Linting with black failed."
+      #     fi
 
-          if [ "${{steps.pylint.outcome}}" != "success" ]; then
-            echo "Linting with pylint failed."
-          fi
+      #     if [ "${{steps.pylint.outcome}}" != "success" ]; then
+      #       echo "Linting with pylint failed."
+      #     fi
 
-          exit 1
+      #     exit 1
